plugins {
    id 'java'
}

group = rootProject.group
version = rootProject.version

base {
    archivesName.set('ASMP_voxy-debug')
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release.set(21)
}

dependencies {
    compileOnly project(':')
}

sourceSets.main.compileClasspath += rootProject.sourceSets.main.output + rootProject.configurations.compileClasspath
sourceSets.main.runtimeClasspath += rootProject.sourceSets.main.output + rootProject.configurations.runtimeClasspath

tasks.named('compileJava') {
    dependsOn rootProject.tasks.named('classes')
}

tasks.named('processResources') {
    def properties = [
            version  : rootProject.version,
            minecraft: providers.gradleProperty('minecraft_version').get()
    ]
    inputs.properties properties
    filesMatching('META-INF/neoforge.mods.toml') {
        expand properties
    }
}

tasks.named('jar') {
    destinationDirectory.set(rootProject.layout.buildDirectory.dir('tmp/embeddedDebug'))
}
