org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=false

# Mod
mod_id=voxy
mod_name=Voxy
mod_version=0.2.15-beta
maven_group=me.cortex

# Minecraft / NeoForge
minecraft_version=1.21.1
neoforge_version=21.1.229

# Mods
sodium_version=0.8.12+mc1.21.1
lithium_version=mc1.21.1-0.15.3-neoforge
iris_version=1.8.12+1.21.1-neoforge
sodium_extra_version=mc1.21.1-0.6.0+neoforge
cloth_config_version=15.0.140
chunky_version=1.4.23-neoforge
spark_version=1.10.152-neoforge
vivecraft_version=1.21.9-1.3.2-neoforge
nvidium_version=0.4.1-beta9:1.21-1.21.1@jar
flashback_version=rNCr1Rbs

# Embedded libraries
jedis_version=5.1.0
rocksdb_version=10.2.1
commons_pool_version=2.12.0
lz4_version=1.8.0
xz_version=1.10
sqlite_jdbc_version=3.49.1.0
