org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=false

# Mod
mod_id=voxy
mod_name=Voxy
mod_version=0.2.152-beta
maven_group=me.cortex

# Minecraft / NeoForge
minecraft_version=1.21.1
neoforge_version=21.1.229

# Mods
sodium_version=0.8.12+mc1.21.1
iris_version=1.8.12+1.21.1-neoforge
nvidium_version=0.4.1-beta9:1.21-1.21.1@jar
