#version 450
#extension GL_ARB_gpu_shader_int64 : enable

layout(local_size_x = 128) in;

#define DRAW_BUFFER_BINDING 1
#define DRAW_COUNT_BUFFER_BINDING 2
#define SECTION_METADATA_BUFFER_BINDING 3
#define VISIBILITY_BUFFER_BINDING 4
#define INDIRECT_SECTION_LOOKUP_BINDING 5
#define POSITION_SCRATCH_BINDING 6
#define POSITION_SCRATCH_ACCESS writeonly

#import <voxy:lod/section.glsl>
#import <voxy:lod/gl46/bindings.glsl>

//https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_shader_16bit_storage.txt
// adds support for uint8_t which can use for compact visibility buffer


layout(binding = TRANSLUCENT_DISTANCE_BUFFER_BINDING, std430) restrict buffer TranslucentCommandCount {
    uint[] translucentCommandData;
};

//Note: if i want reverse indexing i need to use the index buffer offset to offset
void writeCmd(uint idx, uint offset, uint quadCount, uvec2 position) {
    DrawCommand cmd;
    cmd.count = quadCount * 6;
    cmd.instanceCount = 1;
    cmd.firstIndex = 0;
    cmd.baseVertex = 0;
    cmd.baseInstance = idx;
    cmdBuffer[idx] = cmd;
    positionBuffer[idx] = uvec4(position, offset, 0);
}

void main() {
    if (gl_GlobalInvocationID.x >= sectionCount) {
        return;
    }
    uint sectionId = indirectLookup[gl_GlobalInvocationID.x];
    SectionMeta meta = sectionData[sectionId];
    uint detail = extractDetail(meta);
    ivec3 ipos = extractPosition(meta);

    uint dat = visibilityData[sectionId];

    //if the section was visible this frame
    bool shouldRender = (dat&0x7fffffffu) == frameId;
    bool renderTemporally = (dat&0x80000000u)==0;// means, if it was not visible last frame



    if (shouldRender) {
        uint ptr = extractQuadStart(meta);
        ivec3 relative = ipos-(baseSectionPos>>detail);
        uint drawId = gl_GlobalInvocationID.x;

        uvec2 rawPosition = extractRawPos(meta);
        uvec4 countsA = meta.b;
        uvec4 countsB = meta.c;

        //TODO implicit command merging
        uint msk = 0;
        msk |= uint((countsA.z!=0) && (relative.y>-1))<<0;
        msk |= uint((countsA.w!=0) && (relative.y<1 ))<<1;
        msk |= uint((countsB.x!=0) && (relative.z>-1))<<2;
        msk |= uint((countsB.y!=0) && (relative.z<1 ))<<3;
        msk |= uint((countsB.z!=0) && (relative.x>-1))<<4;
        msk |= uint((countsB.w!=0) && (relative.x<1 ))<<5;

        msk |= uint(countsA.y!=0)<<6;


        uint cmdCnt = bitCount(msk);
        uint cmdPtr = atomicAdd(opaqueDrawCount, cmdCnt);

        uint tCmdPtr = 0;
        if (renderTemporally) {
            tCmdPtr = atomicAdd(temporalOpaqueDrawCount, cmdCnt) + TEMPORAL_OFFSET;
        }

        uint count = 0;
        //Translucency
        count = countsA.x;
        if (count != 0) {
            uint tp = atomicAdd(translucentDrawCount, 1)+TRANSLUCENT_WRITE_BASE;
            translucentCommandData[tp] = drawId;
            uvec3 absRel = abs(relative);
            uint distToCamera = (absRel.x+absRel.y+absRel.z)<<detail;
            //The -1 is because we want 0 to TRANSLUCENT_WRITE_BASE, exclusive of ending, not inclusive (0->1023)
            distToCamera = (TRANSLUCENT_WRITE_BASE-1)-min(distToCamera, (TRANSLUCENT_WRITE_BASE-1));
            atomicAdd(translucentCommandData[distToCamera], 1);
        }
        ptr += count;

        //Double sided quads
        count = countsA.y;
        if (count != 0) {
            writeCmd(cmdPtr++, ptr, count, rawPosition);
            if (renderTemporally) {
                writeCmd(tCmdPtr++, ptr, count, rawPosition);
            }
        }
        ptr += count;

        //Down
        count = countsA.z;
        if (((msk&(1u<<0))!=0)) {
            writeCmd(cmdPtr++, ptr, count, rawPosition);
            if (renderTemporally) {
                writeCmd(tCmdPtr++, ptr, count, rawPosition);
            }
        }
        ptr += count;

        //Up
        count = countsA.w;
        if ((msk&(1u<<1))!=0) {
            writeCmd(cmdPtr++, ptr, count, rawPosition);
            if (renderTemporally) {
                writeCmd(tCmdPtr++, ptr, count, rawPosition);
            }
        }
        ptr += count;

        //North
        count = countsB.x;
        if ((msk&(1u<<2))!=0) {
            writeCmd(cmdPtr++, ptr, count, rawPosition);
            if (renderTemporally) {
                writeCmd(tCmdPtr++, ptr, count, rawPosition);
            }
        }
        ptr += count;

        //South
        count = countsB.y;
        if ((msk&(1u<<3))!=0) {
            writeCmd(cmdPtr++, ptr, count, rawPosition);
            if (renderTemporally) {
                writeCmd(tCmdPtr++, ptr, count, rawPosition);
            }
        }
        ptr += count;

        //West
        count = countsB.z;
        if ((msk&(1u<<4))!=0) {
            writeCmd(cmdPtr++, ptr, count, rawPosition);
            if (renderTemporally) {
                writeCmd(tCmdPtr++, ptr, count, rawPosition);
            }
        }
        ptr += count;

        //East
        count = countsB.w;
        if ((msk&(1u<<5))!=0) {
            writeCmd(cmdPtr++, ptr, count, rawPosition);
            if (renderTemporally) {
                writeCmd(tCmdPtr++, ptr, count, rawPosition);
            }
        }
        ptr += count;

    }
}
