modLoader="javafml"
loaderVersion="[1,)"
license="All-Rights-Reserved"
[[mods]]
modId="voxy_server"
version="${version}"
displayName="Voxy Server"
description='''Spatial terrain service and automatic updates for Voxy.'''
displayTest="IGNORE_ALL_VERSION"
[[dependencies.voxy_server]]
modId="neoforge"
type="required"
versionRange="[${neoforge},)"
side="SERVER"
[[dependencies.voxy_server]]
modId="minecraft"
type="required"
versionRange="[${minecraft}]"
side="SERVER"
