modLoader="javafml"
loaderVersion="[1,)"
license="All-Rights-Reserved"

[[mods]]
modId="voxy_minecraft_bridge"
version="${version}"
displayName="Voxy Minecraft Bridge"
description='''Runs and advertises the Rust Voxy backend and relays it through Minecraft when configured.'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.voxy_minecraft_bridge]]
modId="neoforge"
type="required"
versionRange="[$neoforge,)"
ordering="NONE"
side="SERVER"

[[dependencies.voxy_minecraft_bridge]]
modId="minecraft"
type="required"
versionRange="[$minecraft]"
ordering="NONE"
side="SERVER"
