modLoader="javafml"
loaderVersion="[1,)"
license="All-Rights-Reserved"

[[mods]]
modId="voxy_debug"
version="${version}"
displayName="Voxy Diagnostics"
description='''Optional diagnostics and repair tools for Voxy.'''
displayTest="IGNORE_ALL_VERSION"
authors="ASMP"

[[mixins]]
config="voxy.debug.mixins.json"

[[dependencies.voxy_debug]]
modId="voxy"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.voxy_debug]]
modId="neoforge"
type="required"
versionRange="[21.1.229,)"
ordering="NONE"
side="BOTH"

[[dependencies.voxy_debug]]
modId="minecraft"
type="required"
versionRange="[${minecraft}]"
ordering="NONE"
side="BOTH"
