# Version-specific properties for 1.20.1 Forge
deps.minecraft=1.20.1
stonecutter.loader=legacyforge
forge_version=47.4.20
# Library versions
lwjglVersion=3.3.1
deps.embeddium=0.3.31+mc1.20.1
deps.oculus=1.20.1-1.8.0
deps.radium=0.12.4
deps.nvidium_maven=maven.modrinth
deps.nvidium=0.2.6-beta-1.20.1
deps.iris=1.7.6+1.20.1
deps.sodium.extra=mc1.20.1-0.5.9
deps.chunky=1.3.146-forge
deps.spark=1.10.53-forge
deps.fabric.permissions=0.3.1
deps.vivecraft=1.20.1-1.3.2-forge
deps.flashback=rNCr1Rbs